### ISSUE TITLE
net/http/pprof breaks with Martini

### ISSUE THREAD

**Issue by apiguy** [go-martini/martini#228]
It appears that Martini prevents `net/http/pprof` from working. This can be reproduced by creating a non-Martini app and an equivalent Martini app and examining the "/debug/pprof/" endpoints.

To reproduce:

If you create the following non-Martini application:

``` go
// Non-Martini version
package main

import (
    "fmt"
    "net/http"
    _ "net/http/pprof"
)

func handler(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "Hi there, I love %s!", r.URL.Path[1:])
}

func main() {
    http.HandleFunc("/", handler)
    http.ListenAndServe(":8080", nil)
}
```

When running this and then navigating to http://localhost:8080/debug/pprof/ you'll see the following:

![screen shot 2014-04-09 at 2 48 32 pm](https://cloud.githubusercontent.com/assets/163848/2661716/c87024ea-c030-11e3-9f3b-8ab03983e0d1.png)

If you create the equivalent Martini based application:

``` go
// Martini Version
package main

import (
    "fmt"
    "github.com/go-martini/martini"
    "net/http"
    _ "net/http/pprof"
)

func handler(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "Hi there, I love %s!", r.URL.Path[1:])
}

func main() {
    m := martini.New()
    r := martini.NewRouter()
    r.Get("/", handler)
    m.Action(r.Handle)
    http.ListenAndServe(":8080", m)
}
```

And navigate to the same endpoint, you get a 404.

**Comment by rcshubhadeep** [comment]
@tarrsalah  The code link you given is no longer working. I really need this to figure out what is happening with my set up as I can not get it working. I am using martini classic and m.Run()

Also, I was wondering if the results are similar of manual profiling... I really need to know which function is killing the web service. My web service takes too long time.

**Comment by tarrsalah** [comment]
@rcshubhadeep  It's been so long since I have read or written any martini related code , so honestly I have no idea what's going on in the martini community, sorry!

**Comment by rcshubhadeep** [comment]
Hi,

Sorry, I think it was a mis communication from my side what I waned to mean is that the link gives me 404 error. So it will be really great to see the code once if possible. Rest I can check myself.

Please let me know

**Comment by tarrsalah** [comment]
Oh yeah, 
I deleted the code while ago, I believe that it is totally obsolete, take a look at this  [code](https://github.com/gohttp/pprof/blob/master/pprof.go), may help you.

**Comment by DavidVaini** [comment]
The code is deleted, I took at look at that link of code and it doesnt run, anyone have the original code snippet? Otherwise this is still an issue for me.
