### ISSUE TITLE
Static middleware is 404ing on everything

### ISSUE THREAD

**Issue by dkulchenko** [go-martini/martini#278]
I updated from a two month old version of Martini to master today, and the static middleware doesn't work at all:

daniilk:~ ∞ curl http://localhost:3000/test.js
404 page not found
daniilk:~ ∞ curl http://localhost:3000/public/test.js
404 page not found
daniilk:~ ∞

Here's the source:

``` go
package main

import "github.com/go-martini/martini"

func main() {
    m := martini.Classic()
    m.Use(martini.Static("public"))
    m.Run()
}
```

and my directory listing:

daniilk:~/testcase ∞ ls -lR
total 8
drwxr-xr-x  3 daniilk  staff  102 Jun 27 18:02 public
-rw-r--r--  1 daniilk  staff  136 Jun 27 18:04 server.go

./public:
total 8
-rw-r--r--  1 daniilk  staff  16 Jun 27 18:02 test.js
daniilk:~/testcase ∞

I'm running it via "go run server.go".

Possibly caused by d6dbf549f64849bc0ba4585e2ec62d0dacf311c6.

**Comment by liu-xiao-guo** [comment]
It seem that it is broken again. I just cannot make it work. I get the same problem.
