### ISSUE TITLE
[new middleware] fizz

### ISSUE THREAD

**Issue by xyproto** [go-martini/martini#306]
Hi,

After writing the "permissions" middleware for Negroni, I made some adaptations so that it works with Martini as well. This new middleware for handling users and permissions is called "fizz" (as in Gin Fizz...) and is located at: https://github.com/xyproto/fizz 

Feel free to include it in martini-contrib, if you think it's a suitable addition.

Hope this is the right place/way to ask for middleware to be included.

Best regards,
Alexander Rødseth

**Comment by xyproto** [comment]
Hi,

After looking more at both fizz and permissions2, I found that the examples for using permissions2 + martini were simple enough to not need a wrapper (which were fizz). So I removed fizz.

If http://github.com/xyproto/permissions2 could be added to the list of Martini middleware, that would be great.

Best regards,
Alexander Rødseth

**Comment by mvader** [comment]
Added to the list :-)

**Comment by xyproto** [comment]
Thanks :+1:
