### ISSUE TITLE
Error handling middleware in Martini

### ISSUE THREAD

**Issue by vgalu** [go-martini/martini#319]
Hello,

What would be the idiomatic way of pushing all error handling into a dedicated middleware at the end of the handler chain?

Each function implementing an API call would return as soon as the first error occurs, the error being then picked up by this specialized middleware that would map between different error types and HTTP response codes.

In my particular scenario I need all handlers to not return anything and take at least an http.ResponseWriter and an http.Request as arguments.

I am currently trying to map error objects to the Martini context and pick them up later from the middleware, but keep running into "Value not found for type" panics. I am quite sure I am doing this the wrong way around.

Thanks!

**Comment by schickling** [comment]
+1
