### ISSUE TITLE
Return 405 Not Allowed if route is not defined

### ISSUE THREAD

**Issue by sybrandy** [go-martini/martini#330]
Hello,

I just started using Martini and I noticed that if I try to make a request that's not supported, I get a 404 instead of a 405.  Would it be possible to change this to return the 405 instead?

Also, if you read the RESTful Web APIs book by O'Reilly, it is suggested that you return the following header to alert the client to what methods are supported:

    Allow: GET, POST

Thanks!

**Comment by talbright** [comment]
I'm not sure what you mean by "request that's not supported". If you mean the route is correct, but the method is not supported, that should be a 405. Otherwise all things being equal, a 404 is correct. 

http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by sybrandy** [comment]
Yes, you are correct.  The route is correct, but the method is not supported.

**Comment by talbright** [comment]
I've submitted a PR for this. In the meantime you can implement this yourself with your own handler, see https://gist.github.com/talbright/b63761338d14803ce371 for an example.

**Comment by talbright** [comment]
Just found this too :flushed:

https://github.com/martini-contrib/strict
