### ISSUE TITLE
Typo in the README?

### ISSUE THREAD

**Issue by gitdvcs** [go-martini/martini#338]
I'm nearly finished my German translation of the project's README file. Is it possible that some words are missing in the first sentence of the `Next()` paragraph?

'Middleware Handlers can call to yield **the until** after the other Handlers'

**Comment by jayrox** [comment]
>Middleware Handlers can call to yield the until after the other Handlers  

i think the "the" is extra, and should be read as  

>Middleware Handlers can call Next() to yield until after the other Handlers

**Comment by gitdvcs** [comment]
Thanks for the quick response. I'll make a pull request with the translation soon.
