### ISSUE TITLE
Trying to build app with GAE

### ISSUE THREAD

**Issue by mblasi** [go-martini/martini#357]
Hi! I have a go-martini app, and it is working fine if I start it wih 'go run server.go'.
Now, I'm trying to run it with google cloud services. (https://cloud.google.com/sdk/gcloud-app)
Firs step is to start it locally in a local google app engine (gcloud preview app run app.yml)
This is the error I'm getting:

$ gcloud preview app run app.yml
Module [default] found in file [/home/matias/sandbox/my-app/app.yml]
INFO 2015-05-07 12:40:12,220 devappserver2.py:745] Skipping SDK update check.
WARNING 2015-05-07 12:40:27,266 simple_search_stub.py:1126] Could not read search indexes from /tmp/appengine.factor-idea.matias/search_indexes
INFO 2015-05-07 12:40:27,267 api_server.py:190] Starting API server at: http://localhost:47005
INFO 2015-05-07 12:40:27,507 dispatcher.py:192] Starting module "default" running at: http://localhost:8080
INFO 2015-05-07 12:40:27,508 admin_server.py:118] Starting admin server at: http://localhost:8000
ERROR 2015-05-07 12:40:29,037 go_runtime.py:171] Failed to build Go application: (Executed command: /home/matias/google-cloud-sdk/platform/google_appengine/goroot/bin/go-app-builder -app_base /home/matias/sandbox/my-app -arch 6 -dynamic -goroot .....
...
...

2015/05/07 09:40:29 go-app-builder: Failed parsing input: package "src/github.com/garyburd/redigo/redisx" cannot import internal package "github.com/garyburd/redigo/internal"

I already asked about that in redigo project, but I'm still trying to solve it: https://github.com/garyburd/redigo/issues/122

Do you have any clue about this?

Best regards,
Matías.

**Comment by bezigon** [comment]
Maybe related to https://stackoverflow.com/questions/30478485/im-really-confused-with-importing-required-packages-but-all-its-files-were-excl
