### ISSUE TITLE
Out of memory when i test web using loaderrunner 

### ISSUE THREAD

**Issue by figoxu** [go-martini/martini#374]
When i using loaderRunner test my web site  using loaderRunner with 50 JavaVUser. After 2Minute, the linux kill the programe with the reason of lack memory.
![loadderrunner](https://cloud.githubusercontent.com/assets/10055828/9219830/55c7a564-4110-11e5-8251-506d2777a51d.png)
The go program memory shows as follow image
![oom001](https://cloud.githubusercontent.com/assets/10055828/9219840/6fa97804-4110-11e5-85b2-fb100cc780ad.png)

**Comment by jinxiao** [comment]
well , we have met the same problem , it seems that this framework doesn't work well on garbage collection

**Comment by figoxu** [comment]
I reduce the number of Vuser from 50 to 10.  After the 4 minutes, It was shut down with the reason of lack memory.

![loadderrunner](https://cloud.githubusercontent.com/assets/10055828/9220199/39a288ba-4113-11e5-8c82-634e35c936dc.png)
![oom_10vuser](https://cloud.githubusercontent.com/assets/10055828/9220201/3c335172-4113-11e5-8e2d-9dc3129c8aaa.png)
It seems like there is a memory leak problem in the martini framework ? Is that right ?

**Comment by figoxu** [comment]
I reduce the number of Vuser from 50 to 10. After the 4 minutes, It was shut down with the reason of lack memory.
![a](https://cloud.githubusercontent.com/assets/10055828/9220355/9817c562-4114-11e5-91f4-825b7f635ec6.png)
![b](https://cloud.githubusercontent.com/assets/10055828/9220358/9b697396-4114-11e5-8f69-68cca83ce608.png)

It seems like there is a memory leak problem in the martini framework ? Is that right ?

**Comment by figoxu** [comment]
The pereformace of http.Server() in go lang is good.
![vuser1000](https://cloud.githubusercontent.com/assets/10055828/9222400/2771b542-4124-11e5-9585-9f0edff46fa1.png)
![vuser5000](https://cloud.githubusercontent.com/assets/10055828/9222402/2b320966-4124-11e5-9b29-faf8dffce38e.png)

**Comment by mvader** [comment]
The framework is no longer under development since a few months ago. It may have a bug or something but I don't think is going to be solved.

**Comment by figoxu** [comment]
I try to reduce the execute time of martini middleware, The memory recycle problem seems to be solved .

**Comment by mvader** [comment]
If you're running into performance issues you could use https://github.com/gin-gonic/gin which has a pretty great performance.
