### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by quandrei** [go-martini/martini#384]
Not a technical issue, but rather having to do with the github repo info itself.

The website: http://martini.codegangsta.io/ 
referenced on: https://github.com/go-martini/martini

Seems to be down. Not sure if you are aware or if it has been moved. Wasn't sure where else to advise you of this.

Thanks.

**Comment by mvader** [comment]
That's something @codegangsta should look into.

Anyway, the framework is no longer maintained so I don't think it's worth it to put it back online.
