### ISSUE TITLE
Reasons why it's no longer maintained?

### ISSUE THREAD

**Issue by rashthedude** [go-martini/martini#385]
I'd like to know what the driving forces or reasons were to ditch this project?

**Comment by hut8** [comment]
The original author has a good explanation here:

https://web.archive.org/web/20140521180901/http://codegangsta.io:80/blog/2014/05/19/my-thoughts-on-martini/

Edited to replace faulty link with @erizocosmico 's link

**Comment by AnneTheAgile** [comment]
The above blog references a followup project that also appears abandoned.
https://github.com/codegangsta/negroni

**Comment by wiredprairie** [comment]
@hut8 -the link you provided now is for an online casino ....   You may want to remove the link.

**Comment by erizocosmico** [comment]
@wiredprairie https://web.archive.org/web/20140521180901/http://codegangsta.io:80/blog/2014/05/19/my-thoughts-on-martini/
