### ISSUE TITLE
Add support for fasthttp

### ISSUE THREAD

**Issue by valyala** [go-martini/martini#389]
[fasthttp](https://github.com/valyala/fasthttp) provides high-performance http server. It outperforms [net/http](https://golang.org/pkg/net/http/) by 1.5x-3x in production and by 10x in [synthetic benchmarks](https://github.com/valyala/fasthttp#http-server-performance-comparison-with-nethttp). It would be great if martini adds fasthttp support additionally to net/http.

p.s.: I know that [martini is no longer maintained](https://codegangsta.io/blog/2014/05/19/my-thoughts-on-martini/), but I hope martini community may ressurect it and add fasthttp support :)

**Comment by mvader** [comment]
You suggest adding 1.5x-3x performance in HTTP but using a slow framework (hello, reflection), which does not make much sense in the end. The aforementioned reason is why the framework is no longer maintained.

Maybe try with http://github.com/gin-gonic/gin, it'd be cool if it was even faster

**Comment by valyala** [comment]
@mvader , I already filed [feature request for gin](https://github.com/gin-gonic/gin/issues/498)
