### ISSUE TITLE
The mainpage http://martini.codegangsta.io show ERR NAME RESOLVED in china.

### ISSUE THREAD

**Issue by codeskyblue** [go-martini/martini#390]

**Comment by mvader** [comment]
So does in every other country. I think the page is down. But, anyway, the framework is no longer maintained.

**Comment by codeskyblue** [comment]
@mvader Do you known some alternatives ?

**Comment by mvader** [comment]
@codeskyblue https://github.com/gin-gonic/gin is imho, the best one right now
