### ISSUE TITLE
Hi, 'http://martini.codegangsta.io' is not reachable

### ISSUE THREAD

**Issue by xuxiangyang** [go-martini/martini#395]
I can not open the http://martini.codegangsta.io because that can not find record in DNS.

I am in china, run `nslookup martini.codegangsta.io`

```
Server:         219.141.136.10
Address:        219.141.136.10#53

** server can't find martini.codegangsta.io: NXDOMAIN
```

I run nslookup on aws in Japan
```
Server:         172.31.0.2
Address:        172.31.0.2#53

** server can't find martini.codegangsta.io: NXDOMAIN
```

how can I get the web?
Thx

**Comment by mvader** [comment]
You can't, it's not online anymore. In fact, the framework is no longer maintained.

**Comment by xuxiangyang** [comment]
oh..sorry for heard that. could you recommend some frameworks?  Thx

**Comment by mvader** [comment]
https://github.com/gin-gonic/gin is my framework of choice now.

**Comment by xuxiangyang** [comment]
thx
