### ISSUE TITLE
Using context.Context in Handlers

### ISSUE THREAD

**Issue by aedenj** [go-martini/martini#404]
I'm relatively new to Go and have inherited a few services written in it using Martini. I'd like to use the context.Context in Go 1.7 for the typical use case of storing a user id. It's unclear to me how i can store the user id and have it available to other handlers. Any help would be appreciated.

**Comment by mvader** [comment]
You can do this:

```go
func myCtxMiddleware(c martini.Context) {
        c.Map(context.Background())
}
```

and then get the context like this:
```go
func Handler(ctx context.Context) {
        // use ctx
}
```
