### ISSUE TITLE
Does martini really support html5 Mode serving of static files?

### ISSUE THREAD

**Issue by andela-hkoske** [go-martini/martini#405]
In this repo's [README.md](https://github.com/go-martini/martini/blob/master/README.md), it's claimed that one of martini's features is that it supports:

> Default document serving (e.g., for serving AngularJS apps in HTML5 mode).

How does one go about this? Nothing is mentioned on the [martini godoc documentation](https://godoc.org/github.com/go-martini/martini).

**Comment by mvader** [comment]
Hi, you can find how to do that in this part of the README: https://github.com/go-martini/martini/blob/master/README.md#serving-a-default-document
