### ISSUE TITLE
Website hacked?

### ISSUE THREAD

**Issue by gabrielrinaldi** [go-martini/martini#412]
I think your website got hacked. At least it does not seem related to martini at all 😞 

<img width="1495" alt="screen shot 2017-07-26 at 4 03 03 pm" src="https://user-images.githubusercontent.com/38957/28647424-f7a3d25c-721b-11e7-9960-385c20e2e50a.png">

**Comment by erizocosmico** [comment]
The domain might have not been renewed, that looks like a parking page. 

Anyway, the framework is no longer maintained.
