### ISSUE TITLE
Swagger Integration (Feature Request)

### ISSUE THREAD

**Issue by ghost** [go-martini/martini#63]
Hi

First of all, nice project. I like it a lot.

Some feature that would make this project even more attractive is support for swagger.

Swagger is a specification and complete framework implementation for describing, producing, consuming, and visualizing RESTful web services.

Website: https://developers.helloreverb.com/swagger/
Example: http://petstore.swagger.wordnik.com/

Swagger is already supported by play-framework, scalatra, django, go-restful.

BR, Rene

**Comment by jgimenez** [comment]
This has been useful for me: https://github.com/yvasiyarov/swagger
